[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Datetime library."
name = "small_time"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "25.3.0"
license = "MIT"
license-file = "LICENSE"
homepage = "https://github.com/thatstoasty/small-time"
repository = "https://github.com/thatstoasty/small-time"

[tasks]
tests = "python scripts/util.py run tests"
benchmarks = "python scripts/util.py run benchmarks"
examples = "python scripts/util.py run examples"
template = "python scripts/util.py templater"
build = { cmd = "python scripts/util.py build", env = {MODULAR_MOJO_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo"} }
publish = { cmd = "python scripts/util.py publish", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }
bp = { depends-on=["build", "publish"] }

[dependencies]
max = ">=25.3.0,<25.4.0"
