"""Generate morrow/_locale_data.mojo from Arrow 1.4.0's locales.

Run from the repository root:

    uv run --with arrow==1.4.0 python tools/gen_locale_data.py          # rewrite
    uv run --with arrow==1.4.0 python tools/gen_locale_data.py --check  # verify

`--check` leaves the file alone and exits non-zero, printing a short diff, when
the committed file differs from the generated one. Arrow is a development
oracle only, never a Morrow runtime dependency.

Every value comes from Arrow except the hand overrides in `OVERRIDES` below:

- am: Arrow repeats the "seconds" text for future "hours"; use the hours text.
- zh-cn, zh-tw: keep Morrow 1.0's Chinese text (names, abbreviations,
  meridians, "日" ordinals, "立即", no word separator, quarter frames), and
  zh-cn is named "zh-cn" with a "zh-hans" alias; zh-tw gets "zh-hant".

Arrow's method overrides (`_format_timeframe`, `_format_relative`,
`describe_multi`) map to the rule names Morrow implements in locale.mojo; see
`PLURAL_RULES`, `RELATIVE_RULES` and `MULTI_RULES`.
"""
import difflib
from pathlib import Path
import re
import sys

import arrow.locales as L

OUT = Path(__file__).resolve().parent.parent / "morrow" / "_locale_data.mojo"
FRAMES = list(L.TimeFrameLiteral.__args__)
FIELD, ITEM = "\x1f", "\x1e"

HEADER = '''"""Built-in locale records used by `Locale`.

Generated by tools/gen_locale_data.py from Arrow 1.4.0
(https://github.com/arrow-py/arrow, Apache License 2.0); do not edit by hand.
The generator documents its overrides: an Amharic correction for future hours,
and Simplified and Traditional Chinese keep Morrow's 1.0 text. The record field
order is documented in locale.mojo; `\\x1f` separates a key from its text and
`\\x1e` separates items.
"""
'''

# Rule names Morrow implements for each Arrow class that overrides a method.
PLURAL_RULES = {
    "AmharicLocale": "future_if_positive",
    "ArabicLocale": "arabic",
    "CroatianLocale": "double",
    "CzechLocale": "czech",
    "EstonianLocale": "future_if_positive",
    "FinnishLocale": "past_if_negative",
    "HebrewLocale": "hebrew",
    "HungarianLocale": "future_if_positive",
    "IcelandicLocale": "icelandic",
    "MalteseLocale": "maltese",
    "SerbianLocale": "double",
    "SinhalaLocale": "future_if_positive",
    "SlavicBaseLocale": "slavic",
    "SlovakLocale": "czech",
    "ZuluLocale": "future_if_positive",
}
RELATIVE_RULES = {
    "KoreanLocale": "korean",
    "LaotianLocale": "compact_seconds",
    "ThaiLocale": "compact_seconds",
}
MULTI_RULES = {"HebrewLocale": "hebrew"}

# Hand overrides, by Morrow locale name. Keys are fields of `fields()`;
# a "timeframes" dict replaces only the frames it names.
_ZH = {
    "month_abbreviations": [f"{m}月" for m in range(1, 13)],
    "meridians": ["上午", "下午", "上午", "下午"],
    "separator": "",
    "instantly": "立即",
    "ordinals": [f"{n}日" for n in range(1, 32)],
    "ordinal_digits": "0",
}
OVERRIDES = {
    "am": {"timeframes": {"hours": {"past": "ከ {0} ሰዓታት", "future": "በ {0} ሰዓታት"}}},
    "zh-cn": {
        **_ZH,
        "aliases": ["zh", "zh-cn", "zh-hans"],
        "day_abbreviations": "周一 周二 周三 周四 周五 周六 周日".split(),
        "timeframes": {"now": "刚刚", "quarter": "1个季度", "quarters": "{0}个季度"},
    },
    "zh-tw": {
        **_ZH,
        "aliases": ["zh-tw", "zh-hant"],
        "month_names": "一月 二月 三月 四月 五月 六月 七月 八月 九月 十月 十一月 十二月".split(),
        "day_names": "星期一 星期二 星期三 星期四 星期五 星期六 星期日".split(),
        "day_abbreviations": "週一 週二 週三 週四 週五 週六 週日".split(),
        "and_word": "",
        "timeframes": {"now": "剛剛", "quarter": "1個季度", "quarters": "{0}個季度"},
    },
}


def norm(name):
    return name.lower().replace("_", "-")


def owner(cls, method):
    return next(c.__name__ for c in cls.__mro__ if method in vars(c))


def pairs(mapping):
    return ITEM.join(f"{key}{FIELD}{text}" for key, text in mapping.items())


def timeframe(value):
    """Encode a timeframe as "text" or "key\\x1ftext\\x1e..." items."""
    if isinstance(value, str):
        return value
    items = {}
    for key, form in value.items():
        if isinstance(form, str):
            items[key] = form
        else:  # Czech/Slovak future forms: [singular, paucal]
            items[f"{key}-singular"], items[f"{key}-paucal"] = form
    return pairs(items)


def fields(cls):
    """Arrow's data for one locale class, with OVERRIDES applied."""
    loc = cls()
    aliases = [norm(name) for name in cls.names]
    distance = getattr(cls, "timeframes_only_distance", {})
    f = {
        "name": aliases[0],
        "aliases": aliases,
        "month_names": loc.month_names[1:],
        "month_abbreviations": loc.month_abbreviations[1:],
        "day_names": loc.day_names[1:],
        "day_abbreviations": loc.day_abbreviations[1:],
        "meridians": [loc.meridians[k] for k in ("am", "pm", "AM", "PM")],
        "past": cls.past,
        "future": cls.future,
        "and_word": cls.and_word or "",
        "separator": " ",
        "plural_rule": PLURAL_RULES.get(owner(cls, "_format_timeframe"), ""),
        "relative_rule": RELATIVE_RULES.get(owner(cls, "_format_relative"), ""),
        "multi_rule": MULTI_RULES.get(owner(cls, "describe_multi"), ""),
        "instantly": "instantly" if cls is L.EnglishLocale else "",
        "year_offset": str(int(loc.year_full(2000)) - 2000),
        "ordinals": [loc._ordinal_number(n) for n in range(1, 32)],
        "ordinal_day_re": cls.ordinal_day_re,
        "ordinal_digits": "1" if cls.ordinal_day_re == L.Locale.ordinal_day_re else "0",
        "special_days": pairs(getattr(cls, "special_dayframes", {})),
        "special_years": pairs(getattr(cls, "special_yearframes", {})),
        "timeframes": {frame: cls.timeframes.get(frame, "") for frame in FRAMES},
        "distance": {frame: distance.get(frame, "") for frame in FRAMES},
    }
    if cls is L.ChineseCNLocale:
        f["name"] = "zh-cn"
    override = OVERRIDES.get(f["name"], {})
    f.update({k: v for k, v in override.items() if k != "timeframes"})
    f["timeframes"].update(override.get("timeframes", {}))
    return f


def ordinal_parse(f):
    """ "day\\x1ftext" pairs that parse as ordinals beyond the formatted text."""
    texts = f["ordinals"]
    found = {(n, text) for n, text in enumerate(texts, 1)}
    pattern = f["ordinal_day_re"]
    if pattern != L.Locale.ordinal_day_re:
        # Also accept every suffix in the pattern's character classes (es "1ª").
        suffixes = "".join(re.findall(r"\[([^\]\d-]+)\]", pattern))
        found |= {(n, f"{n}{c}") for n in range(1, 32) for c in suffixes}
        found = {p for p in found if re.fullmatch(pattern, p[1])}
    return ITEM.join(f"{n}{FIELD}{text}" for n, text in sorted(found))


def record(f):
    plain = f["ordinals"] == [str(n) for n in range(1, 32)]
    return (
        [f["name"]]
        + f["month_names"]
        + f["month_abbreviations"]
        + f["day_names"]
        + f["day_abbreviations"]
        + f["meridians"]
        + [f[k] for k in ("past", "future", "and_word", "separator")]
        + [f[k] for k in ("plural_rule", "relative_rule", "multi_rule")]
        + [f["instantly"], f["year_offset"]]
        + (["", ""] if plain else [FIELD.join(f["ordinals"]), ordinal_parse(f)])
        + [f["ordinal_digits"], f["special_days"], f["special_years"]]
        + [timeframe(f["timeframes"][frame]) for frame in FRAMES]
        + [timeframe(f["distance"][frame]) for frame in FRAMES]
    )


def literal(text):
    """A string literal; like `mojo format`, quote with ' to avoid escaping "."""
    quote = "'" if '"' in text and "'" not in text else '"'
    out = []
    for c in text:
        if c in quote + "\\":
            out.append("\\" + c)
        elif c.isprintable():
            out.append(c)
        else:
            out.append(repr(c)[1:-1])
    return quote + "".join(out) + quote


def list_item(text):
    """A record item laid out as `mojo format` does: a string longer than the
    80-column line is split before spaces into parenthesized chunks."""
    s = literal(text)
    if 8 + len(s) + 1 <= 80 or " " not in s:
        return f"        {s},\n"
    chunks = []
    while 12 + len(s) > 80:
        # Last space that keeps `"chunk"` within 80 columns at indent 12 and
        # leaves at least 6 characters on both sides.
        cut = max((i for i in range(6, min(67, len(s) - 6) + 1) if s[i] == " "), default=None)
        if cut is None:
            break
        chunks.append(s[:cut] + '"')
        s = '"' + s[cut:]
    body = "".join(f"            {c}\n" for c in chunks + [s])
    return f"        (\n{body}        ),\n"


def string_list(items, indent):
    """A list literal, on one line when it fits in 80 columns."""
    pad = " " * indent
    one_line = "[" + ", ".join(literal(i) for i in items) + "]"
    if len(pad) + len("return ") + len(one_line) <= 80:
        return one_line
    body = "".join(f"{pad}    {literal(i)},\n" for i in items)
    return f"[\n{body}{pad}]"


def render(locales):
    out = [HEADER, f"comptime LOCALE_COUNT = {len(locales)}"]
    index = {f["name"]: i for i, f in enumerate(locales)}
    out.append(f"comptime LOCALE_ZH_CN = {index['zh-cn']}")
    out.append(f"comptime LOCALE_ZH_TW = {index['zh-tw']}\n\n")

    out.append("def _locale_index(name: String) -> Int:")
    out.append("    if name.byte_length() == 0:\n        return -1")
    out.append('    var key = name.lower().replace("_", "-")')
    out.append("    var first = Int(key.as_bytes()[0])")
    groups = {}
    for i, f in enumerate(locales):
        for alias in f["aliases"]:
            groups.setdefault(ord(alias[0]), []).append((alias, i))
    for first in sorted(groups):
        out.append(f"    if first == {first}:")
        for alias, i in groups[first]:
            out.append(f'        if key == "{alias}":\n            return {i}')
        out.append("        return -1")
    out.append("    return -1\n\n")

    names = string_list([f["name"] for f in locales], 4)
    out.append(f"def _locale_names() -> List[String]:\n    return {names}\n\n")

    out.append("def _locale_aliases(index: Int) -> List[String]:")
    for i, f in enumerate(locales):
        out.append(f"    if index == {i}:\n        return {string_list(f['aliases'], 8)}")
    out.append("    return []\n\n")

    out.append("def _locale_record(index: Int) -> List[String]:")
    for i in range(len(locales)):
        out.append(f"    if index == {i}:\n        return _record_{i}()")
    out.append("    return []\n")

    for i, f in enumerate(locales):
        items = "".join(list_item(v) for v in record(f))
        out.append(f"\ndef _record_{i}() -> List[String]:\n    return [\n{items}    ]\n")
    return "\n".join(out)


def generate():
    classes = set(L._locale_map.values())
    locales = sorted((fields(cls) for cls in classes), key=lambda f: f["name"])
    locales.sort(key=lambda f: f["name"] != "en")  # English is index 0
    return render(locales)


if __name__ == "__main__":
    text = generate()
    if "--check" not in sys.argv[1:]:
        OUT.write_text(text, encoding="utf-8")
        sys.exit(0)
    current = OUT.read_text(encoding="utf-8")
    if current != text:
        diff = difflib.unified_diff(
            current.splitlines(), text.splitlines(), "committed", "generated", lineterm=""
        )
        print("\n".join(list(diff)[:40]))
        print(f"{OUT.name} is out of date; run tools/gen_locale_data.py")
        sys.exit(1)
