context:
  version: "0.8.0"

package:
  name: morrow
  version: ${{ version }}

source:
  - git: https://github.com/mojoto/morrow.mojo.git
    rev: v0.8.0

build:
  number: 1
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo precompile morrow -o ${PREFIX}/lib/mojo/morrow.mojoc

requirements:
  build:
    - mojo-compiler ==${{ mojo_version }}
  host:
    - mojo-compiler ==${{ mojo_version }}
  run:
    - mojo-compiler ==${{ mojo_version }}

tests:
  - script:
      - if: unix
        then:
          - mojo run test.mojo
    files:
      recipe:
        - test.mojo

about:
  homepage: https://github.com/mojoto/morrow.mojo
  repository: https://github.com/mojoto/morrow.mojo
  license: Apache-2.0
  license_file: LICENSE
  summary: Human-friendly date and time utilities for Mojo.

extra:
  project_name: Morrow
  maintainers:
    - Prodesire
