name: Build and Release

env:
  PACKAGE_NAME: morrow.mojopkg
  MORROW_SRC: morrow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -ssL https://magic.modular.com | bash
          BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" )
          echo 'export PATH="$PATH:$HOME/.modular/bin"' >> "$BASHRC"
          source "$BASHRC" && make install
      - name: Build
        run: |
          BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" )
          source "$BASHRC" &&  magic run mojo package ${{ env.MORROW_SRC }} -o ${{ github.workspace }}/${{ env.PACKAGE_NAME }}
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ github.workspace }}/${{ env.PACKAGE_NAME }}
