name: Build and Release

env:
  PACKAGE_NAME: morrow.mojopkg

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          make install
      - name: Build
        run: make build
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ github.workspace }}/${{ env.PACKAGE_NAME }}
