name: Build and Release

env:
  PACKAGE_NAME: morrow.mojopkg
  MORROW_SRC: morrow
  MOJO_HOME: /home/runner/.modular/pkg/packages.modular.com_mojo/bin

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl https://get.modular.com | MODULAR_AUTH=${{ secrets.MODULAR_AUTH }} sh - 
          modular install mojo
      - name: Build
        run: |
          ${{ env.MOJO_HOME }}/mojo package ${{ env.MORROW_SRC }} -o ${{ github.workspace }}/${{ env.PACKAGE_NAME }}
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ github.workspace }}/${{ env.PACKAGE_NAME }}
