name: Run Tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          make install
      - name: Test
        run: make test
