name: Run Tests

on: [pull_request, push]

env:
  PACKAGE_NAME: morrow.mojopkg
  MORROW_SRC: morrow

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          curl -ssL https://magic.modular.com | bash
          BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" )
          echo 'export PATH="$PATH:$HOME/.modular/bin"' >> "$BASHRC"
          source "$BASHRC" && make install
      - name: Test
        run: |
          BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" )
          source "$BASHRC" && make test
